export interface KeywordEstimate {
  niche: "health" | "fitness" | "home" | "office" | "travel" | "other";
  selling_price_usd: number;
  alibaba_cost_range: string;
  estimated_margin_pct: number;
  weight_kg: number;
  has_recurring_purchase: boolean;
  cross_sell_opportunities: string[];
  is_evergreen: boolean;
  is_giftable: boolean;
  is_simple_to_manufacture: boolean;
  est_moq: number;
}

export const KEYWORD_ESTIMATES: Record<string, KeywordEstimate> = {
  "red light therapy device": {
    niche: "health",
    selling_price_usd: 80,
    alibaba_cost_range: "$15-30",
    estimated_margin_pct: 75,
    weight_kg: 0.4,
    has_recurring_purchase: false,
    cross_sell_opportunities: ["face mask therapy", "skin serum", "collagen supplement"],
    is_evergreen: true,
    is_giftable: true,
    is_simple_to_manufacture: false,
    est_moq: 300,
  },
  "neck traction device": {
    niche: "health",
    selling_price_usd: 55,
    alibaba_cost_range: "$8-18",
    estimated_margin_pct: 76,
    weight_kg: 0.3,
    has_recurring_purchase: false,
    cross_sell_opportunities: ["cervical pillow", "back posture corrector", "heating pad"],
    is_evergreen: true,
    is_giftable: true,
    is_simple_to_manufacture: true,
    est_moq: 100,
  },
  "knee compression sleeve": {
    niche: "health",
    selling_price_usd: 35,
    alibaba_cost_range: "$4-10",
    estimated_margin_pct: 74,
    weight_kg: 0.15,
    has_recurring_purchase: true,
    cross_sell_opportunities: ["ankle brace", "resistance bands", "joint supplement"],
    is_evergreen: true,
    is_giftable: true,
    is_simple_to_manufacture: true,
    est_moq: 100,
  },
  "back posture corrector": {
    niche: "health",
    selling_price_usd: 45,
    alibaba_cost_range: "$6-14",
    estimated_margin_pct: 75,
    weight_kg: 0.2,
    has_recurring_purchase: false,
    cross_sell_opportunities: ["lumbar support pillow", "ergonomic wrist rest", "under desk foot rest"],
    is_evergreen: true,
    is_giftable: true,
    is_simple_to_manufacture: true,
    est_moq: 100,
  },
  "cervical neck stretcher": {
    niche: "health",
    selling_price_usd: 40,
    alibaba_cost_range: "$5-12",
    estimated_margin_pct: 74,
    weight_kg: 0.25,
    has_recurring_purchase: false,
    cross_sell_opportunities: ["neck traction device", "heating pad", "cervical pillow"],
    is_evergreen: true,
    is_giftable: true,
    is_simple_to_manufacture: true,
    est_moq: 100,
  },
  "trigger point massage tool": {
    niche: "health",
    selling_price_usd: 35,
    alibaba_cost_range: "$5-11",
    estimated_margin_pct: 72,
    weight_kg: 0.3,
    has_recurring_purchase: false,
    cross_sell_opportunities: ["acupressure mat set", "fascia gun mini", "massage oil"],
    is_evergreen: true,
    is_giftable: true,
    is_simple_to_manufacture: true,
    est_moq: 100,
  },
  "fascia gun mini": {
    niche: "health",
    selling_price_usd: 60,
    alibaba_cost_range: "$12-22",
    estimated_margin_pct: 75,
    weight_kg: 0.45,
    has_recurring_purchase: false,
    cross_sell_opportunities: ["massage gun attachment heads", "resistance loop bands set", "muscle cream"],
    is_evergreen: true,
    is_giftable: true,
    is_simple_to_manufacture: false,
    est_moq: 300,
  },
  "eye massager electric": {
    niche: "health",
    selling_price_usd: 55,
    alibaba_cost_range: "$10-20",
    estimated_margin_pct: 75,
    weight_kg: 0.35,
    has_recurring_purchase: false,
    cross_sell_opportunities: ["eye cream", "blue light glasses", "sleep mask"],
    is_evergreen: true,
    is_giftable: true,
    is_simple_to_manufacture: false,
    est_moq: 300,
  },
  "led face mask therapy": {
    niche: "health",
    selling_price_usd: 90,
    alibaba_cost_range: "$18-35",
    estimated_margin_pct: 78,
    weight_kg: 0.35,
    has_recurring_purchase: false,
    cross_sell_opportunities: ["skin serum", "red light therapy device", "collagen supplement"],
    is_evergreen: true,
    is_giftable: true,
    is_simple_to_manufacture: false,
    est_moq: 300,
  },
  "microcurrent face lifting device": {
    niche: "health",
    selling_price_usd: 85,
    alibaba_cost_range: "$16-30",
    estimated_margin_pct: 77,
    weight_kg: 0.2,
    has_recurring_purchase: false,
    cross_sell_opportunities: ["conductive gel", "skin serum", "led face mask therapy"],
    is_evergreen: true,
    is_giftable: true,
    is_simple_to_manufacture: false,
    est_moq: 300,
  },
  "ice globes face roller": {
    niche: "health",
    selling_price_usd: 35,
    alibaba_cost_range: "$4-9",
    estimated_margin_pct: 78,
    weight_kg: 0.15,
    has_recurring_purchase: false,
    cross_sell_opportunities: ["face serum", "gua sha tool", "jade roller"],
    is_evergreen: true,
    is_giftable: true,
    is_simple_to_manufacture: true,
    est_moq: 100,
  },
  "blackhead remover vacuum": {
    niche: "health",
    selling_price_usd: 45,
    alibaba_cost_range: "$7-15",
    estimated_margin_pct: 75,
    weight_kg: 0.2,
    has_recurring_purchase: false,
    cross_sell_opportunities: ["pore strips", "sonic facial cleanser", "face mask"],
    is_evergreen: true,
    is_giftable: true,
    is_simple_to_manufacture: false,
    est_moq: 300,
  },
  "sonic facial cleanser": {
    niche: "health",
    selling_price_usd: 50,
    alibaba_cost_range: "$8-16",
    estimated_margin_pct: 76,
    weight_kg: 0.2,
    has_recurring_purchase: true,
    cross_sell_opportunities: ["replacement brush heads", "face wash", "toner"],
    is_evergreen: true,
    is_giftable: true,
    is_simple_to_manufacture: false,
    est_moq: 300,
  },
  "nail care electric drill": {
    niche: "health",
    selling_price_usd: 40,
    alibaba_cost_range: "$6-14",
    estimated_margin_pct: 73,
    weight_kg: 0.25,
    has_recurring_purchase: true,
    cross_sell_opportunities: ["nail drill bits set", "nail lamp uv", "nail polish gel"],
    is_evergreen: true,
    is_giftable: true,
    is_simple_to_manufacture: false,
    est_moq: 300,
  },
  "resistance loop bands set": {
    niche: "fitness",
    selling_price_usd: 30,
    alibaba_cost_range: "$3-8",
    estimated_margin_pct: 75,
    weight_kg: 0.3,
    has_recurring_purchase: true,
    cross_sell_opportunities: ["ab wheel roller core", "jump rope weighted", "workout gloves"],
    is_evergreen: true,
    is_giftable: true,
    is_simple_to_manufacture: true,
    est_moq: 100,
  },
  "ab wheel roller core": {
    niche: "fitness",
    selling_price_usd: 30,
    alibaba_cost_range: "$4-9",
    estimated_margin_pct: 72,
    weight_kg: 0.5,
    has_recurring_purchase: false,
    cross_sell_opportunities: ["resistance loop bands set", "jump rope weighted", "gym mat"],
    is_evergreen: true,
    is_giftable: true,
    is_simple_to_manufacture: true,
    est_moq: 100,
  },
  "grip strength trainer": {
    niche: "fitness",
    selling_price_usd: 25,
    alibaba_cost_range: "$3-7",
    estimated_margin_pct: 72,
    weight_kg: 0.15,
    has_recurring_purchase: false,
    cross_sell_opportunities: ["wrist wraps", "resistance loop bands set", "hand therapy putty"],
    is_evergreen: true,
    is_giftable: true,
    is_simple_to_manufacture: true,
    est_moq: 100,
  },
  "acupressure mat set": {
    niche: "fitness",
    selling_price_usd: 45,
    alibaba_cost_range: "$7-15",
    estimated_margin_pct: 75,
    weight_kg: 0.5,
    has_recurring_purchase: false,
    cross_sell_opportunities: ["trigger point massage tool", "yoga strap", "foam roller"],
    is_evergreen: true,
    is_giftable: true,
    is_simple_to_manufacture: true,
    est_moq: 100,
  },
  "cold plunge portable": {
    niche: "fitness",
    selling_price_usd: 120,
    alibaba_cost_range: "$30-55",
    estimated_margin_pct: 70,
    weight_kg: 2.5,
    has_recurring_purchase: false,
    cross_sell_opportunities: ["sauna blanket infrared", "recovery supplement", "cold therapy gel pack"],
    is_evergreen: false,
    is_giftable: true,
    is_simple_to_manufacture: false,
    est_moq: 300,
  },
  "sauna blanket infrared": {
    niche: "fitness",
    selling_price_usd: 110,
    alibaba_cost_range: "$25-45",
    estimated_margin_pct: 72,
    weight_kg: 2.0,
    has_recurring_purchase: false,
    cross_sell_opportunities: ["cold plunge portable", "detox supplement", "workout towel"],
    is_evergreen: false,
    is_giftable: true,
    is_simple_to_manufacture: false,
    est_moq: 300,
  },
  "vacuum seal food bags": {
    niche: "home",
    selling_price_usd: 25,
    alibaba_cost_range: "$4-9",
    estimated_margin_pct: 70,
    weight_kg: 0.3,
    has_recurring_purchase: true,
    cross_sell_opportunities: ["vacuum seal machine", "silicone stretch lids", "pantry organizer"],
    is_evergreen: true,
    is_giftable: false,
    is_simple_to_manufacture: true,
    est_moq: 100,
  },
  "over door organizer hooks": {
    niche: "home",
    selling_price_usd: 22,
    alibaba_cost_range: "$3-7",
    estimated_margin_pct: 68,
    weight_kg: 0.4,
    has_recurring_purchase: false,
    cross_sell_opportunities: ["drawer dividers set", "shoe rack", "closet organizer"],
    is_evergreen: true,
    is_giftable: false,
    is_simple_to_manufacture: true,
    est_moq: 100,
  },
  "drawer dividers set": {
    niche: "home",
    selling_price_usd: 20,
    alibaba_cost_range: "$3-6",
    estimated_margin_pct: 68,
    weight_kg: 0.35,
    has_recurring_purchase: false,
    cross_sell_opportunities: ["over door organizer hooks", "label maker", "storage bins"],
    is_evergreen: true,
    is_giftable: false,
    is_simple_to_manufacture: true,
    est_moq: 100,
  },
  "silicone stretch lids": {
    niche: "home",
    selling_price_usd: 20,
    alibaba_cost_range: "$3-6",
    estimated_margin_pct: 72,
    weight_kg: 0.2,
    has_recurring_purchase: true,
    cross_sell_opportunities: ["vacuum seal food bags", "reusable shopping bags folding", "beeswax food wrap"],
    is_evergreen: true,
    is_giftable: false,
    is_simple_to_manufacture: true,
    est_moq: 100,
  },
  "herb stripper kitchen tool": {
    niche: "home",
    selling_price_usd: 18,
    alibaba_cost_range: "$2-5",
    estimated_margin_pct: 70,
    weight_kg: 0.1,
    has_recurring_purchase: false,
    cross_sell_opportunities: ["spice rack magnetic", "digital kitchen scale", "herb scissors"],
    is_evergreen: true,
    is_giftable: true,
    is_simple_to_manufacture: true,
    est_moq: 100,
  },
  "spice rack magnetic": {
    niche: "home",
    selling_price_usd: 35,
    alibaba_cost_range: "$6-14",
    estimated_margin_pct: 72,
    weight_kg: 0.5,
    has_recurring_purchase: false,
    cross_sell_opportunities: ["herb stripper kitchen tool", "digital kitchen scale", "wall-mount shelves"],
    is_evergreen: true,
    is_giftable: true,
    is_simple_to_manufacture: true,
    est_moq: 100,
  },
  "digital kitchen scale": {
    niche: "home",
    selling_price_usd: 22,
    alibaba_cost_range: "$4-9",
    estimated_margin_pct: 70,
    weight_kg: 0.4,
    has_recurring_purchase: false,
    cross_sell_opportunities: ["spice rack magnetic", "meal prep containers", "food thermometer"],
    is_evergreen: true,
    is_giftable: true,
    is_simple_to_manufacture: false,
    est_moq: 300,
  },
  "monitor riser stand": {
    niche: "office",
    selling_price_usd: 40,
    alibaba_cost_range: "$7-15",
    estimated_margin_pct: 72,
    weight_kg: 0.8,
    has_recurring_purchase: false,
    cross_sell_opportunities: ["cable management clips", "desk pad leather mat", "laptop stand portable"],
    is_evergreen: true,
    is_giftable: true,
    is_simple_to_manufacture: true,
    est_moq: 100,
  },
  "cable management clips": {
    niche: "office",
    selling_price_usd: 18,
    alibaba_cost_range: "$2-5",
    estimated_margin_pct: 75,
    weight_kg: 0.1,
    has_recurring_purchase: true,
    cross_sell_opportunities: ["desk pad leather mat", "monitor riser stand", "cable sleeve organizer"],
    is_evergreen: true,
    is_giftable: false,
    is_simple_to_manufacture: true,
    est_moq: 100,
  },
  "ergonomic wrist rest": {
    niche: "office",
    selling_price_usd: 28,
    alibaba_cost_range: "$4-9",
    estimated_margin_pct: 73,
    weight_kg: 0.25,
    has_recurring_purchase: false,
    cross_sell_opportunities: ["desk pad leather mat", "blue light glasses", "under desk foot rest"],
    is_evergreen: true,
    is_giftable: true,
    is_simple_to_manufacture: true,
    est_moq: 100,
  },
  "laptop stand portable": {
    niche: "office",
    selling_price_usd: 45,
    alibaba_cost_range: "$7-16",
    estimated_margin_pct: 74,
    weight_kg: 0.35,
    has_recurring_purchase: false,
    cross_sell_opportunities: ["monitor riser stand", "cable management clips", "desk pad leather mat"],
    is_evergreen: true,
    is_giftable: true,
    is_simple_to_manufacture: true,
    est_moq: 100,
  },
  "under desk foot rest": {
    niche: "office",
    selling_price_usd: 35,
    alibaba_cost_range: "$6-13",
    estimated_margin_pct: 73,
    weight_kg: 0.5,
    has_recurring_purchase: false,
    cross_sell_opportunities: ["ergonomic wrist rest", "back posture corrector", "lumbar support pillow"],
    is_evergreen: true,
    is_giftable: true,
    is_simple_to_manufacture: true,
    est_moq: 100,
  },
  "blue light glasses": {
    niche: "office",
    selling_price_usd: 35,
    alibaba_cost_range: "$4-10",
    estimated_margin_pct: 78,
    weight_kg: 0.1,
    has_recurring_purchase: false,
    cross_sell_opportunities: ["eye massager electric", "desk pad leather mat", "screen privacy filter"],
    is_evergreen: true,
    is_giftable: true,
    is_simple_to_manufacture: true,
    est_moq: 100,
  },
  "desk pad leather mat": {
    niche: "office",
    selling_price_usd: 40,
    alibaba_cost_range: "$6-15",
    estimated_margin_pct: 75,
    weight_kg: 0.4,
    has_recurring_purchase: false,
    cross_sell_opportunities: ["cable management clips", "ergonomic wrist rest", "monitor riser stand"],
    is_evergreen: true,
    is_giftable: true,
    is_simple_to_manufacture: true,
    est_moq: 100,
  },
  "compression packing cubes": {
    niche: "travel",
    selling_price_usd: 30,
    alibaba_cost_range: "$5-11",
    estimated_margin_pct: 72,
    weight_kg: 0.25,
    has_recurring_purchase: false,
    cross_sell_opportunities: ["travel jewelry organizer", "neck wallet rfid", "portable luggage scale"],
    is_evergreen: true,
    is_giftable: true,
    is_simple_to_manufacture: true,
    est_moq: 100,
  },
  "travel jewelry organizer": {
    niche: "travel",
    selling_price_usd: 25,
    alibaba_cost_range: "$4-9",
    estimated_margin_pct: 72,
    weight_kg: 0.15,
    has_recurring_purchase: false,
    cross_sell_opportunities: ["compression packing cubes", "neck wallet rfid", "travel cosmetic bag"],
    is_evergreen: true,
    is_giftable: true,
    is_simple_to_manufacture: true,
    est_moq: 100,
  },
  "portable luggage scale": {
    niche: "travel",
    selling_price_usd: 20,
    alibaba_cost_range: "$3-7",
    estimated_margin_pct: 70,
    weight_kg: 0.1,
    has_recurring_purchase: false,
    cross_sell_opportunities: ["compression packing cubes", "travel jewelry organizer", "luggage tag"],
    is_evergreen: true,
    is_giftable: true,
    is_simple_to_manufacture: false,
    est_moq: 300,
  },
  "neck wallet rfid": {
    niche: "travel",
    selling_price_usd: 22,
    alibaba_cost_range: "$3-7",
    estimated_margin_pct: 72,
    weight_kg: 0.08,
    has_recurring_purchase: false,
    cross_sell_opportunities: ["compression packing cubes", "travel jewelry organizer", "money belt"],
    is_evergreen: true,
    is_giftable: true,
    is_simple_to_manufacture: true,
    est_moq: 100,
  },
  "reusable shopping bags folding": {
    niche: "home",
    selling_price_usd: 18,
    alibaba_cost_range: "$2-5",
    estimated_margin_pct: 70,
    weight_kg: 0.15,
    has_recurring_purchase: true,
    cross_sell_opportunities: ["silicone stretch lids", "vacuum seal food bags", "produce mesh bags"],
    is_evergreen: true,
    is_giftable: false,
    is_simple_to_manufacture: true,
    est_moq: 100,
  },
  "jump rope weighted": {
    niche: "fitness",
    selling_price_usd: 30,
    alibaba_cost_range: "$5-11",
    estimated_margin_pct: 72,
    weight_kg: 0.45,
    has_recurring_purchase: false,
    cross_sell_opportunities: ["resistance loop bands set", "ab wheel roller core", "skipping mat"],
    is_evergreen: true,
    is_giftable: true,
    is_simple_to_manufacture: true,
    est_moq: 100,
  },
};
