export const KEYWORDS_2025: string[] = [
  "red light therapy device",
  "neck traction device",
  "knee compression sleeve",
  "back posture corrector",
  "cervical neck stretcher",
  "trigger point massage tool",
  "fascia gun mini",
  "eye massager electric",
  "led face mask therapy",
  "microcurrent face lifting device",
  "ice globes face roller",
  "blackhead remover vacuum",
  "sonic facial cleanser",
  "nail care electric drill",
  "resistance loop bands set",
  "ab wheel roller core",
  "grip strength trainer",
  "acupressure mat set",
  "cold plunge portable",
  "sauna blanket infrared",
  "vacuum seal food bags",
  "over door organizer hooks",
  "drawer dividers set",
  "silicone stretch lids",
  "herb stripper kitchen tool",
  "spice rack magnetic",
  "digital kitchen scale",
  "monitor riser stand",
  "cable management clips",
  "ergonomic wrist rest",
  "laptop stand portable",
  "under desk foot rest",
  "blue light glasses",
  "desk pad leather mat",
  "compression packing cubes",
  "travel jewelry organizer",
  "portable luggage scale",
  "neck wallet rfid",
  "reusable shopping bags folding",
  "jump rope weighted",
];

export const KEYWORDS_PER_RUN = 15;
